spring.application.name=ox_quiz
#mysql \uC5F0\uACB0
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/quiz_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PW}
#\uD658\uACBD\uBCC0\uC218 \uC124\uC815\uC740 edit configuration > modify options > environment variables \uCCB4\uD06C > edit environment variables\uC5D0\uC11C DB_USER=; DB_PW= \uC124\uC815

#sql \uB85C\uADF8
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

### \uD14C\uC774\uBE14 \uC790\uB3D9 \uC0DD\uC131 \uC804\uB7B5
#create : \uC2E4\uD589\uD558\uBA74 \uAE30\uC874 \uD14C\uC774\uBE14 \uB0A0\uB824\uBC84\uB9AC\uACE0 \uC0C8\uB85C \uB9CC\uB4E6(\uADF8\uB798\uC11C \uC798 \uC548 \uC500)
#update
#validate : \uD14C\uC774\uBE14\uC774 \uC62C\uBC14\uB978\uC9C0\uB9CC \uCCB4\uD06C
#none
spring.jpa.hibernate.ddl-auto=update

# SQL \uBC14\uC778\uB529 \uD30C\uB77C\uBBF8\uD130 \uB85C\uADF8
logging.level.org.hibernate.orm.jdbc.bind=trace

# \uBC29\uC5B8\uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
